version: "3"

services:
  api:
    build: ./api
    image: demo-api
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0.3

  nginx:
    image: nginx:1.25.2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api

  api-tests:
    build: ./tests
    image: demo-api-tests
    volumes:
      - ./tests:/etc/newman
    command: run DevOps_in_a_nutshell.postman_collection.json -r cli,htmlextra
    depends_on:
      - nginx

  api-docs:
    image: swaggerapi/swagger-ui:v5.0.0
    volumes:
      - ./api/openapi.yml:/mnt/openapi.yml
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/mnt/openapi.yml
