version: "3"

services:
  api:
    build: ./api
    image: demo-api
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0.3

  nginx:
    image: nginx:1.25.2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - api

  api-tests:
    build: ./tests
    image: demo-api-tests
    volumes:
      - ./tests:/etc/newman
    command: run DevOps_in_a_nutshell.postman_collection.json -r cli,htmlextra
    depends_on:
      - nginx

  api-docs:
    image: swaggerapi/swagger-ui:v5.0.0
    volumes:
      - ./api/openapi.yml:/mnt/openapi.yml
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/mnt/openapi.yml

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    depends_on:
      - api

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
