# Use the official Postman Newman image as the base image
FROM postman/newman:latest

# Install newman-reporter-html globally
RUN npm install -g newman-reporter-htmlextra

# Set the default command to run newman
CMD ["newman"]

