name: API Testing with Newman

on: workflow_dispatch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build API service
        run: docker-compose build api

      - name: Start API service
        run: docker-compose up -d api nginx

      - name: Build testing environment
        run: docker-compose build api-tests

      - name: API testing with newman
        run: |
          docker-compose up -d api-tests
          docker logs ${{ github.event.repository.name }}_api-tests_1

      - name: Get testing results
        uses: actions/upload-artifact@v3
        with:
          name: api-testing-result
          path: tests/newman/
