name: API Testing with Newman

on:
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build API service
        run: docker-compose build

      - name: Start API service & API Testing with Newman
        run: docker-compose up -d

      - name: Get testing results
        uses: actions/upload-artifact@v3
        with:
          - name: api-testing-result
          - ./tests/newman/
