name: API Testing with Newman

on:
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Build API service
        run: docker-compose build
        working-directory: ./api

      - name: Start API service
        run: docker-compose up -d
        working-directory: ./api

      - name: API Testing with Newman
        run: newman run api_testing_collection.json --folder RESTful-API
        working-directory: ./tests

