name: API Testing with Newman

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build API service
        run: docker-compose build

      - name: Start API service
        run: docker-compose up -d api nginx mongodb

      - name: API testing with newman
        run: docker-compose up api-tests

      - name: Get testing results
        uses: actions/upload-artifact@v3
        with:
          name: api-testing-result
          path: tests/newman/
